language: rust
os:
- linux
rust:
- stable
- nightly
matrix:
  include:
  - name: "rustfmt"
    rust: nightly
    before_script:
    - rustup component add rustfmt
    script:
    - cargo fmt --all -- --check
  fast_finish: true
cache: cargo
branches:
  only:
  - staging
  - trying