[server]
address = "127.0.0.1"
port = 5119

keys = [
    "GLzvuWtyCfHyGhF2",
    "GLzvuWtyCfHyGhF2",
    "GLzvuWtyCfHyGhF2",
    "GLzvuWtyCfHyGhF2",
    "GLzvuWtyCfHyGhF2",
    "GLzvuWtyCfHyGhF2",
    "GLzvuWtyCfHyGhF2",
    "GLzvuWtyCfHyGhF2",
    "GLzvuWtyCfHyGhF2",
    "GLzvuWtyCfHyGhF2",
    "GLzvuWtyCfHyGhF2",
    "GLzvuWtyCfHyGhF2",
    "GLzvuWtyCfHyGhF2",
    "GLzvuWtyCfHyGhF2",
    "GLzvuWtyCfHyGhF2",
    "GLzvuWtyCfHyGhF2",
]